name: CI/CD Docker Hub

on:
  push:
    branches: [ main ]
    paths:
      - 'docsmanagerbackend/**'
      - 'docsManager/docsmanagerbackend/**'
      - '.github/workflows/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'docsmanagerbackend/**'
      - 'docsManager/docsmanagerbackend/**'
      - '.github/workflows/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      # Locate the backend directory robustly
      - name: Locate backend directory
        id: locate
        shell: bash
        run: |
          set -euo pipefail
          if [ -d "docsManager/docsmanagerbackend" ]; then
            echo "app_dir=docsManager/docsmanagerbackend" >> "$GITHUB_OUTPUT"
          elif [ -d "docsmanagerbackend" ]; then
            echo "app_dir=docsmanagerbackend" >> "$GITHUB_OUTPUT"
          else
            echo "ERROR: Could not find backend directory. Searched:" >&2
            echo " - docsManager/docsmanagerbackend" >&2
            echo " - docsmanagerbackend" >&2
            exit 1
          fi
          echo "Resolved app_dir=$(cat $GITHUB_OUTPUT | sed -n 's/^app_dir=//p')"

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Build backend (Maven)
        run: mvn -B -ntp -DskipTests package
        working-directory: ${{ steps.locate.outputs.app_dir }}

      - name: Docker meta (tags)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.IMAGE_NAME || format('{0}/{1}', secrets.DOCKERHUB_USERNAME, github.event.repository.name) }}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=sha,format=short

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: ${{ steps.locate.outputs.app_dir }}
          file: ${{ steps.locate.outputs.app_dir }}/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
