name: CI/CD Docker Hub

on:
  push:
    branches: [ main ]
    paths:
      - 'docsManager/docsmanagerbackend/**'
      - '.github/workflows/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'docsManager/docsmanagerbackend/**'
      - '.github/workflows/**'

env:
  APP_DIR: docsManager/docsmanagerbackend

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Build backend (Maven)
        run: mvn -B -ntp -DskipTests package
        working-directory: ${{ env.APP_DIR }}

      - name: Docker meta (tags)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.IMAGE_NAME || format('{0}/{1}', secrets.DOCKERHUB_USERNAME, github.event.repository.name) }}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=sha,format=short

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: ${{ env.APP_DIR }}
          file: ${{ env.APP_DIR }}/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
